package com.kitsugi.animelist.ui.screens.settings

import com.kitsugi.animelist.ui.components.BackupImportMode
import com.kitsugi.animelist.data.local.CloudstreamRepoEntity
import com.kitsugi.animelist.data.local.CsPluginEntity
import com.kitsugi.animelist.data.local.ManagedAddonEntity
import com.kitsugi.animelist.data.local.MangaSourceStateEntity
import com.kitsugi.animelist.data.remote.CsPlugin

class SettingsScreenParameters(
    val general: GeneralSettings,
    val profile: ProfileSettings,
    val player: PlayerSettings,
    val addon: AddonSettings,
    val manga: MangaSettings,
    val integrations: IntegrationsSettings
)

data class GeneralSettings(
    val selectedThemeId: String,
    val showAdultContent: Boolean,
    val blurAdultMedia: Boolean,
    val selectedListLayoutId: String,
    val selectedHomeLayoutId: String = "classic",
    val onHomeLayoutSelected: (String) -> Unit = {},
    val titleLanguage: String,
    val scoreFormat: String,
    val hideScores: Boolean,
    val showAnimeLogos: Boolean,
    val onThemeSelected: (String) -> Unit,
    val onAdultContentChanged: (Boolean) -> Unit,
    val onBlurAdultMediaChanged: (Boolean) -> Unit,
    val onListLayoutSelected: (String) -> Unit,
    val onTitleLanguageSelected: (String) -> Unit,
    val onScoreFormatSelected: (String) -> Unit,
    val onHideScoresChanged: (Boolean) -> Unit,
    val onShowAnimeLogosChanged: (Boolean) -> Unit,
    val themeMode: String = "FOLLOW_SYSTEM",
    val onThemeModeSelected: (String) -> Unit = {},
    val amoledBlack: Boolean = false,
    val onAmoledBlackChanged: (Boolean) -> Unit = {},
    val customAccentColor: Int = 0,
    val onCustomAccentColorChanged: (Int) -> Unit = {},
    val defaultTab: String = "LAST_USED",
    val onDefaultTabSelected: (String) -> Unit = {},
    val appLanguage: String = "system",
    val onAppLanguageSelected: (String) -> Unit = {},
    val fixedNavBar: Boolean = false,
    val onFixedNavBarChanged: (Boolean) -> Unit = {},
    val airingNotificationsEnabled: Boolean = false,
    val onAiringNotificationsChanged: (Boolean) -> Unit = {},
    val aniListNotificationsEnabled: Boolean = false,
    val onAniListNotificationsChanged: (Boolean) -> Unit = {},
    val malNotificationsEnabled: Boolean = false,
    val onMalNotificationsChanged: (Boolean) -> Unit = {},
    val simklNotificationsEnabled: Boolean = false,
    val onSimklNotificationsChanged: (Boolean) -> Unit = {},
    val notificationInterval: Int = 180,
    val onNotificationIntervalChanged: (Int) -> Unit = {},
    val splashAnimationEnabled: Boolean = true,
    val splashSoundEnabled: Boolean = true,
    val onSplashAnimationEnabledChanged: (Boolean) -> Unit = {},
    val onSplashSoundEnabledChanged: (Boolean) -> Unit = {},
    // ─── T1-06 – Arama Geçmişi ───────────────────────────────────────────────
    val searchHistoryEnabled: Boolean = true,
    val onSearchHistoryEnabledChanged: (Boolean) -> Unit = {},
    // ─── T1-07 – Manga Ayarları ───────────────────────────────────────────
    val mangaReadingMode: String = "RightToLeft",
    val mangaColorFilter: String = "Normal",
    val mangaFitMode: String = "FitScreen",
    val mangaBrightness: Float = 1.0f,
    val onMangaReadingModeSelected: (String) -> Unit = {},
    val onMangaColorFilterSelected: (String) -> Unit = {},
    val onMangaFitModeSelected: (String) -> Unit = {},
    val onMangaBrightnessChanged: (Float) -> Unit = {},
    // ─── Otomatik & Manuel Güncelleme Kontrolü ─────────────────────────
    val autoUpdateCheckEnabled: Boolean = true,
    val onAutoUpdateCheckEnabledChanged: (Boolean) -> Unit = {},
    val onCheckForUpdatesClick: () -> Unit = {},
    val customImageDownloadUri: String = "",
    val onCustomImageDownloadUriChanged: (String) -> Unit = {}
)

data class ProfileSettings(
    val profileName: String,
    val listTitle: String,
    val anilistUsername: String,
    val malUsername: String,
    val profileImageUri: String,
    val bannerImageUri: String,
    val totalEntryCount: Int,
    val backupText: String,
    val importText: String,
    val importMode: BackupImportMode,
    val isAniListConnected: Boolean,
    val isMalConnected: Boolean,
    val isAniListImportRunning: Boolean,
    val isMalImportRunning: Boolean,
    val isSimklConnected: Boolean = false,
    val simklUsername: String = "",
    val isSimklImportRunning: Boolean = false,
    val isSimklSessionExpired: Boolean = false,
    val onProfileInfoSave: (profileName: String, listTitle: String) -> Unit,
    val onPickProfileImageClick: () -> Unit,
    val onPickBannerImageClick: () -> Unit,
    val onClearProfileImageClick: () -> Unit,
    val onClearBannerImageClick: () -> Unit,
    val onAniListAuthClick: () -> Unit,
    val onMalAuthClick: () -> Unit,
    val onAniListImportClick: () -> Unit,
    val onMalImportClick: () -> Unit,
    val onSimklAuthClick: () -> Unit = {},
    val onSimklImportClick: () -> Unit = {},
    val onDeleteAllEntries: () -> Unit,
    val onCreateBackupText: () -> Unit,
    val onImportBackupText: () -> Unit,
    val onClearBackupText: () -> Unit,
    val onClearImportText: () -> Unit,
    val onExportBackupFileClick: () -> Unit,
    val onImportBackupFileClick: () -> Unit,
    val isCrossSyncRunning: Boolean = false,
    val onCrossSyncClick: () -> Unit = {},
    val onImportModeChange: (BackupImportMode) -> Unit,
    val onImportTextChange: (String) -> Unit,
    val syncEnabledAnilist: Boolean = false,
    val syncEnabledMal: Boolean = false,
    val onSyncEnabledAnilistChanged: (Boolean) -> Unit = {},
    val onSyncEnabledMalChanged: (Boolean) -> Unit = {}
)

data class PlayerSettings(
    val playerPreference: String = "INTERNAL",
    val isAutoplayEnabled: Boolean = true,
    val skipIntroDurationSec: Int = 5,
    val defaultSubtitleSize: Int = 16,
    val defaultSubtitleColor: Int = 0xFFFFFFFF.toInt(),
    val subtitleBold: Boolean = false,
    val subtitleOutlineEnabled: Boolean = true,
    val defaultAudioBoost: Float = 0.0f,
    val defaultAudioDelayMs: Long = 0L,
    val minBufferMs: Int = 30_000,
    val maxBufferMs: Int = 60_000,
    val bufferForPlaybackMs: Int = 8_000,
    val bufferForPlaybackAfterRebufferMs: Int = 6_000,
    val backBufferDurationMs: Int = 0,
    val dv7HandlingMode: com.kitsugi.animelist.data.settings.Dv7HandlingMode = com.kitsugi.animelist.data.settings.Dv7HandlingMode.AUTO,
    val stripHdr10PlusSei: Boolean = false,
    val preferredSubtitleLanguages: String = "tr,en",
    val addonSubtitleStartupMode: String = "ALL_SUBTITLES",
    val onPlayerPreferenceSelected: (String) -> Unit = {},
    val onAutoplayEnabledChanged: (Boolean) -> Unit = {},
    val onSkipIntroDurationSecSelected: (Int) -> Unit = {},
    val onDefaultSubtitleSizeSelected: (Int) -> Unit = {},
    val onDefaultSubtitleColorSelected: (Int) -> Unit = {},
    val onSubtitleBoldChanged: (Boolean) -> Unit = {},
    val onSubtitleOutlineEnabledChanged: (Boolean) -> Unit = {},
    val onDefaultAudioBoostSelected: (Float) -> Unit = {},
    val onDefaultAudioDelayMsSelected: (Long) -> Unit = {},
    val onPreferredSubtitleLanguagesSelected: (String) -> Unit = {},
    val onAddonSubtitleStartupModeSelected: (String) -> Unit = {},
    val onBufferSettingsChanged: (min: Int, max: Int, playback: Int, rebuffer: Int, back: Int) -> Unit = { _, _, _, _, _ -> },
    val onDv7HandlingModeSelected: (com.kitsugi.animelist.data.settings.Dv7HandlingMode) -> Unit = {},
    val onStripHdr10PlusSeiChanged: (Boolean) -> Unit = {},
    val qualityProfileJson: String = "{}",
    val onQualityProfileSelected: (String) -> Unit = {},
    val parallelRangeEnabled: Boolean = false,
    val onParallelRangeEnabledChanged: (Boolean) -> Unit = {},
    val frameRateMatchingMode: com.kitsugi.animelist.data.settings.FrameRateMatchingMode = com.kitsugi.animelist.data.settings.FrameRateMatchingMode.OFF,
    val resolutionMatchingEnabled: Boolean = false,
    val onFrameRateMatchingModeSelected: (com.kitsugi.animelist.data.settings.FrameRateMatchingMode) -> Unit = {},
    val onResolutionMatchingEnabledChanged: (Boolean) -> Unit = {},
    val gestureVolumeEnabled: Boolean = true,
    val gestureBrightnessEnabled: Boolean = true,
    val gestureZoomEnabled: Boolean = true,
    val doubleTapSeekSeconds: Int = 10,
    val holdSpeedMultiplier: Float = 2.0f,
    val gestureScrollSensitivity: Float = 1.0f,
    val onGestureVolumeEnabledChanged: (Boolean) -> Unit = {},
    val onGestureBrightnessEnabledChanged: (Boolean) -> Unit = {},
    val onGestureZoomEnabledChanged: (Boolean) -> Unit = {},
    val onDoubleTapSeekSecondsSelected: (Int) -> Unit = {},
    val onHoldSpeedMultiplierSelected: (Float) -> Unit = {},
    val onGestureScrollSensitivityChanged: (Float) -> Unit = {},
    val previewSeekbarEnabled: Boolean = true,
    val onPreviewSeekbarEnabledChanged: (Boolean) -> Unit = {},
    val preferredExternalPlayerPackage: String = "",
    val onPreferredExternalPlayerPackageSelected: (String) -> Unit = {},
    // T1.1 – Görüntü Oranı
    val aspectMode: com.kitsugi.animelist.core.player.PlayerAspectMode = com.kitsugi.animelist.core.player.PlayerAspectMode.ORIGINAL,
    val onAspectModeSelected: (com.kitsugi.animelist.core.player.PlayerAspectMode) -> Unit = {},
    val liveHelperEnabled: Boolean = true,
    val onLiveHelperEnabledChanged: (Boolean) -> Unit = {},
    val enableAssExtractor: Boolean = true,
    val onEnableAssExtractorChanged: (Boolean) -> Unit = {},
    // ─── T2.6 – Oynatıcı Başlık / Medya Bilgisi Görünürlüğü ────────────────
    val showPlayerTitle: Boolean = true,
    val onShowPlayerTitleChanged: (Boolean) -> Unit = {},
    val showPlayerResolution: Boolean = true,
    val onShowPlayerResolutionChanged: (Boolean) -> Unit = {},
    val showMediaInfo: Boolean = true,
    val onShowMediaInfoChanged: (Boolean) -> Unit = {},
    // ─── T1-01 – StillWatching + PostPlayMode + AutoplaySessionLimit ──────────
    val stillWatchingEnabled: Boolean = true,
    val onStillWatchingEnabledChanged: (Boolean) -> Unit = {},
    val stillWatchingThresholdMinutes: Int = 90,
    val onStillWatchingThresholdMinutesChanged: (Int) -> Unit = {},
    val postPlayMode: String = "AUTO_PLAY_NEXT",
    val onPostPlayModeChanged: (String) -> Unit = {},
    val autoplaySessionLimit: Int = 0,
    val onAutoplaySessionLimitChanged: (Int) -> Unit = {},
    // ─── T1-03 – Ses Gelişmiş ────────────────────────────────────────────────
    val gainBoostDb: Float = 0f,
    val onGainBoostDbChanged: (Float) -> Unit = {},
    val subtitleDelayMs: Long = 0L,
    val onSubtitleDelayMsChanged: (Long) -> Unit = {},
    // ─── T1-04 – Dekoder Önceliği (Telefon) ──────────────────────────────────
    val decoderPriority: Int = 0,
    val onDecoderPriorityChanged: (Int) -> Unit = {}
)

data class AddonSettings(
    val addons: List<ManagedAddonEntity>,
    val debridToken: String,
    val repos: List<CloudstreamRepoEntity>,
    val repoPlugins: Map<String, List<CsPlugin>?>,
    val repoLoadingState: Map<String, Boolean>,
    val onAddAddon: (String) -> Unit,
    val onToggleAddon: (ManagedAddonEntity, Boolean) -> Unit,
    val onDeleteAddon: (ManagedAddonEntity) -> Unit,
    val onSaveDebridToken: (String) -> Unit,
    val onAddRepo: (String) -> Unit,
    val onDeleteRepo: (CloudstreamRepoEntity) -> Unit,
    val onFetchRepoPlugins: (String) -> Unit,
    val onInstallPlugin: (CsPlugin, ((Boolean) -> Unit)?) -> Unit,
    val onInstallAllPlugins: (repoUrl: String, repoName: String, plugins: List<CsPlugin>) -> Unit = { _, _, _ -> },
    val onUpdateAllPlugins: (repoUrl: String, repoName: String, plugins: List<CsPlugin>) -> Unit = { _, _, _ -> },
    val bulkInstallRepoUrl: String? = null,
    val bulkInstallRepoName: String? = null,
    val bulkInstallDone: Int = 0,
    val bulkInstallTotal: Int = 0,
    val bulkInstallCurrentName: String = "",
    val bulkInstallResultMessage: String? = null,
    val onClearBulkInstallResult: () -> Unit = {},
    val csPlugins: List<CsPluginEntity> = emptyList(),
    val onToggleCsPlugin: (CsPluginEntity, Boolean) -> Unit = { _, _ -> },
    val onUninstallCsPlugin: (CsPluginEntity) -> Unit = {}
)

data class MangaSettings(
    val mangaSources: List<com.kitsugi.animelist.data.manga.MangaSource> = emptyList(),
    val onInstallMangaExtension: (android.net.Uri) -> Unit = {},
    val onDeleteMangaExtension: (com.kitsugi.animelist.data.manga.MangaSource) -> Unit = {},
    val mangaRepos: List<String> = emptyList(),
    val mangaRepoExtensions: Map<String, List<com.kitsugi.animelist.data.remote.MangaExtensionInfo>?> = emptyMap(),
    val mangaRepoLoadingState: Map<String, Boolean> = emptyMap(),
    val onAddMangaRepo: (String) -> Unit = {},
    val onDeleteMangaRepo: (String) -> Unit = {},
    val onFetchMangaRepo: (String) -> Unit = {},
    val onInstallMangaApk: (com.kitsugi.animelist.data.remote.MangaExtensionInfo, ((Boolean) -> Unit)?) -> Unit = { _, _ -> },
    val onInstallAllMangaExtensions: (repoUrl: String, extensions: List<com.kitsugi.animelist.data.remote.MangaExtensionInfo>) -> Unit = { _, _ -> },
    val onUpdateAllMangaExtensions: (repoUrl: String, extensions: List<com.kitsugi.animelist.data.remote.MangaExtensionInfo>) -> Unit = { _, _ -> },
    val mangaBulkInstallRepoUrl: String? = null,
    val mangaBulkInstallDone: Int = 0,
    val mangaBulkInstallTotal: Int = 0,
    val mangaBulkInstallCurrentName: String = "",
    val onGetInstalledMangaVersionCode: (String) -> Long = { -1L },
    val onGetInstalledMangaVersion: (String) -> String? = { null },
    val onGetMangaSourceHealthStatus: (com.kitsugi.animelist.data.manga.MangaSource) -> com.kitsugi.animelist.data.manga.model.SourceHealthStatus = { com.kitsugi.animelist.data.manga.model.SourceHealthStatus.Unknown },
    val onGetMangaSourceRuntimeStats: (com.kitsugi.animelist.data.manga.MangaSource) -> com.kitsugi.animelist.data.manga.model.SourceRuntimeStats = { com.kitsugi.animelist.data.manga.model.SourceRuntimeStats() },
    val onGetMangaConfiguredDomain: (com.kitsugi.animelist.data.manga.MangaSource) -> String? = { null },
    val onGetMangaConfiguredBaseUrl: (com.kitsugi.animelist.data.manga.MangaSource) -> String = { it.baseUrl },
    val onSetMangaSourceDomain: (com.kitsugi.animelist.data.manga.MangaSource, String?) -> Unit = { _, _ -> },
    val onGetMangaSourceUserAgent: (com.kitsugi.animelist.data.manga.MangaSource) -> String? = { null },
    val onGetMangaSourceSlowdownEnabled: (com.kitsugi.animelist.data.manga.MangaSource) -> Boolean = { false },
    val onSetMangaSourceUserAgent: (com.kitsugi.animelist.data.manga.MangaSource, String?) -> Unit = { _, _ -> },
    val onSetMangaSourceSlowdownEnabled: (com.kitsugi.animelist.data.manga.MangaSource, Boolean) -> Unit = { _, _ -> },
    val onResetMangaSourceDiagnostics: (com.kitsugi.animelist.data.manga.MangaSource) -> Unit = {},
    val onClearAllMangaSourceDiagnostics: () -> Unit = {},
    val onIsMangaSourceBusy: (com.kitsugi.animelist.data.manga.MangaSource) -> Boolean = { false },
    val onQuickCheckMangaSource: (com.kitsugi.animelist.data.manga.MangaSource) -> Unit = {},
    val onRefreshMangaSourceMirror: (com.kitsugi.animelist.data.manga.MangaSource) -> Unit = {},
    val onClearMangaSourceMirror: (com.kitsugi.animelist.data.manga.MangaSource) -> Unit = {},
    val mangaSourceStateReport: List<MangaSourceStateEntity> = emptyList(),
    val onOpenMangaSourceHealthScreen: () -> Unit = {},
    val onForceCheckMangaUpdates: (onResult: (String) -> Unit) -> Unit = {},
    val untrustedRepoToConfirm: String? = null,
    val untrustedSignatureToConfirm: Pair<com.kitsugi.animelist.data.remote.MangaExtensionInfo, String>? = null,
    val onConfirmUntrustedRepo: (String) -> Unit = {},
    val onDismissUntrustedRepo: () -> Unit = {},
    val onConfirmUntrustedSignature: (com.kitsugi.animelist.data.remote.MangaExtensionInfo, String) -> Unit = { _, _ -> },
    val onDismissUntrustedSignature: () -> Unit = {}
)

data class IntegrationsSettings(
    val dnsChoice: Int = 0,
    val onDnsChoiceSelected: (Int) -> Unit = {},
    val tmdbEnabled: Boolean = true,
    val onTmdbEnabledChanged: (Boolean) -> Unit = {},
    val tmdbApiKey: String = "",
    val onTmdbApiKeyChanged: (String) -> Unit = {},
    val tmdbModernHomeEnabled: Boolean = false,
    val onTmdbModernHomeEnabledChanged: (Boolean) -> Unit = {},
    val tmdbEnrichContinueWatching: Boolean = true,
    val onTmdbEnrichContinueWatchingChanged: (Boolean) -> Unit = {},
    val tmdbLanguage: String = "en",
    val onTmdbLanguageChanged: (String) -> Unit = {},
    val tmdbUseArtwork: Boolean = true,
    val onTmdbUseArtworkChanged: (Boolean) -> Unit = {},
    val tmdbUseBasicInfo: Boolean = true,
    val onTmdbUseBasicInfoChanged: (Boolean) -> Unit = {},
    val tmdbUseDetails: Boolean = true,
    val onTmdbUseDetailsChanged: (Boolean) -> Unit = {},
    val tmdbUseReleaseDates: Boolean = true,
    val onTmdbUseReleaseDatesChanged: (Boolean) -> Unit = {},
    val tmdbUseCredits: Boolean = true,
    val onTmdbUseCreditsChanged: (Boolean) -> Unit = {},
    val tmdbUseProductions: Boolean = true,
    val onTmdbUseProductionsChanged: (Boolean) -> Unit = {},
    val tmdbUseNetworks: Boolean = true,
    val onTmdbUseNetworksChanged: (Boolean) -> Unit = {},
    val tmdbUseEpisodes: Boolean = true,
    val onTmdbUseEpisodesChanged: (Boolean) -> Unit = {},
    val tmdbUseTrailers: Boolean = true,
    val onTmdbUseTrailersChanged: (Boolean) -> Unit = {},
    val tmdbUseMoreLikeThis: Boolean = true,
    val onTmdbUseMoreLikeThisChanged: (Boolean) -> Unit = {},
    val tmdbUseCollections: Boolean = true,
    val onTmdbUseCollectionsChanged: (Boolean) -> Unit = {},
    val mdbListEnabled: Boolean = false,
    val onMdbListEnabledChanged: (Boolean) -> Unit = {},
    val mdbListApiKey: String = "",
    val onMdbListApiKeyChanged: (String) -> Unit = {},
    val mdbListShowImdb: Boolean = true,
    val onMdbListShowImdbChanged: (Boolean) -> Unit = {},
    val mdbListShowTomatoes: Boolean = true,
    val onMdbListShowTomatoesChanged: (Boolean) -> Unit = {},
    val mdbListShowMetacritic: Boolean = true,
    val onMdbListShowMetacriticChanged: (Boolean) -> Unit = {},
    val mdbListShowAudience: Boolean = false,
    val onMdbListShowAudienceChanged: (Boolean) -> Unit = {},
    val mdbListShowLetterboxd: Boolean = false,
    val onMdbListShowLetterboxdChanged: (Boolean) -> Unit = {},
    val mdbListShowTmdb: Boolean = false,
    val onMdbListShowTmdbChanged: (Boolean) -> Unit = {},
    val mdbListShowTrakt: Boolean = false,
    val onMdbListShowTraktChanged: (Boolean) -> Unit = {},
    val aniSkipEnabled: Boolean = false,
    val onAniSkipEnabledChanged: (Boolean) -> Unit = {},
    val aniSkipAutoSkip: Boolean = false,
    val onAniSkipAutoSkipChanged: (Boolean) -> Unit = {},
    val animeSkipClientId: String = "",
    val onAnimeSkipClientIdChanged: (String) -> Unit = {},
    val autoTranslateEnabled: Boolean = false,
    val onAutoTranslateEnabledChanged: (Boolean) -> Unit = {},
    val preferredTranslator: String = "DEFAULT",
    val onPreferredTranslatorSelected: (String) -> Unit = {},
    val onOpenStats: () -> Unit = {},
    val onOpenFavourites: () -> Unit = {},
    val onOpenAbout: () -> Unit = {},
    val fanartTvEnabled: Boolean = false,
    val onFanartTvEnabledChanged: (Boolean) -> Unit = {},
    val fanartTvApiKey: String = "",
    val onFanartTvApiKeyChanged: (String) -> Unit = {}
)
