package com.kitsugi.animelist.data.manga

import android.content.Context
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.Request
import org.json.JSONObject
import eu.kanade.tachiyomi.network.NetworkHelper

object MangaCatalogManager {

    private const val TAG = "MangaCatalogManager"

    // Keiyoushi domain override catalog
    private const val CATALOG_URL =
        "https://raw.githubusercontent.com/keiyoushi/extensions/repo/manga_sources_catalog.json"

    // Kotatsu-Redo unified catalog (generated by manga_scanner.py)
    private const val KOTATSU_CATALOG_URL =
        "https://raw.githubusercontent.com/keiyoushi/extensions/repo/kotatsu_catalog.json"

    // GitHub API — latest commit SHA for kotatsu-parsers-redo
    private const val KOTATSU_COMMIT_API =
        "https://api.github.com/repos/Kotatsu-Redo/kotatsu-parsers-redo/commits/master"

    private const val PREFS_NAME               = "manga_catalog_manager"
    private const val KEY_LAST_KOTATSU_SHA     = "last_kotatsu_sha"
    private const val KEY_LAST_KOTATSU_CHECK_MS = "last_kotatsu_check_ms"

    /** Kotatsu commit kontrolü için minimum bekleme süresi (12 saat) */
    private const val KOTATSU_CHECK_INTERVAL_MS = 12L * 60L * 60L * 1000L

    // ─── Keiyoushi Domain Catalog ─────────────────────────────────────────────

    /**
     * Keiyoushi domain override katalog senkronizasyonu.
     */
    suspend fun syncCatalog(context: Context, catalogUrlOverride: String? = null) = withContext(Dispatchers.IO) {
        val rawUrl = catalogUrlOverride ?: CATALOG_URL
        val url = com.kitsugi.animelist.data.remote.MangaRepoClient.applyMirror(rawUrl)
        Log.i(TAG, "Manga domain kataloğu çekiliyor: $url (original: $rawUrl)")

        try {
            val networkHelper = uy.kohesive.injekt.Injekt.get(NetworkHelper::class.java)
            val request = Request.Builder().url(url).build()
            networkHelper.client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    Log.e(TAG, "Katalog çekilemedi (HTTP ${response.code})")
                    return@withContext
                }
                val body = response.body?.string()
                if (body.isNullOrBlank()) {
                    Log.w(TAG, "Katalog içeriği boş")
                    return@withContext
                }
                parseAndApplyCatalog(context, body)
            }
        } catch (e: Exception) {
            Log.e(TAG, "Katalog senkronizasyon hatası: ${e.message}")
        }
    }

    private fun parseAndApplyCatalog(context: Context, jsonStr: String) {
        try {
            val root = JSONObject(jsonStr)
            val sourcesArray = root.optJSONArray("sources") ?: return

            val configStore = SourceConfigStore(context)
            val loadedSources = MangaExtensionLoader.getLoadedSources()
            val sourcesByPkg = loadedSources.associateBy { it.pkgName }

            var updatedCount = 0
            for (i in 0 until sourcesArray.length()) {
                val sourceObj = sourcesArray.optJSONObject(i) ?: continue
                val pkg = sourceObj.optString("pkg", "").trim()
                val activeDomain = sourceObj.optString("active_domain", "").trim()
                if (pkg.isBlank() || activeDomain.isBlank()) continue

                val source = sourcesByPkg[pkg] ?: continue
                val currentDomain = configStore.getActiveDomain(source)
                if (currentDomain != activeDomain) {
                    configStore.setActiveDomain(source, activeDomain)
                    updatedCount++
                    Log.d(TAG, "Domain güncellendi [${source.name}]: $currentDomain -> $activeDomain")
                }
            }
            Log.i(TAG, "Katalog eşitlemesi tamamlandı. $updatedCount kaynak güncellendi.")
        } catch (e: Exception) {
            Log.e(TAG, "Katalog ayrıştırma hatası", e)
        }
    }

    // ─── Kotatsu-Redo Catalog ─────────────────────────────────────────────────

    /**
     * Kotatsu-Redo kaynak senkronizasyonu.
     *
     * 1) GitHub API üzerinden en son commit SHA'sını kontrol eder
     * 2) SHA değiştiyse unified catalog JSON'unu indirir
     * 3) KotatsuExtensionAdapter'ı günceller
     *
     * @param forceCheck  true = 12 saatlik kısıtlamayı atla
     */
    suspend fun syncKotatsuSources(
        context: Context,
        forceCheck: Boolean = false
    ): Int = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val lastCheckMs = prefs.getLong(KEY_LAST_KOTATSU_CHECK_MS, 0L)
        val now = System.currentTimeMillis()

        if (!forceCheck && (now - lastCheckMs) < KOTATSU_CHECK_INTERVAL_MS) {
            val minutesLeft = (KOTATSU_CHECK_INTERVAL_MS - (now - lastCheckMs)) / 60000L
            Log.d(TAG, "Kotatsu kontrol atlandı (sonraki: ${minutesLeft} dk sonra)")
            return@withContext KotatsuExtensionAdapter.getSourceCount()
        }

        prefs.edit().putLong(KEY_LAST_KOTATSU_CHECK_MS, now).apply()
        Log.i(TAG, "Kotatsu-Redo commit SHA kontrolü başlıyor...")

        val networkHelper = try {
            uy.kohesive.injekt.Injekt.get(NetworkHelper::class.java)
        } catch (e: Exception) {
            Log.e(TAG, "NetworkHelper alınamadı: ${e.message}")
            return@withContext KotatsuExtensionAdapter.getSourceCount()
        }

        // 1) GitHub API'dan en son commit SHA'sını çek
        val latestSha = fetchLatestCommitSha(networkHelper) ?: run {
            Log.w(TAG, "Kotatsu commit SHA çekilemedi, güncelleme atlandı.")
            return@withContext KotatsuExtensionAdapter.getSourceCount()
        }

        val savedSha = prefs.getString(KEY_LAST_KOTATSU_SHA, "") ?: ""

        if (latestSha == savedSha && KotatsuExtensionAdapter.getSourceCount() > 0) {
            Log.d(TAG, "Kotatsu güncel (SHA: $latestSha), yeniden indirme atlandı.")
            return@withContext KotatsuExtensionAdapter.getSourceCount()
        }

        Log.i(TAG, "Kotatsu güncelleme gerekli: $savedSha -> $latestSha")

        // 2) Unified catalog JSON'unu indir
        val catalogUrl = com.kitsugi.animelist.data.remote.MangaRepoClient.applyMirror(KOTATSU_CATALOG_URL)
        return@withContext try {
            val request = Request.Builder().url(catalogUrl).build()
            val body = networkHelper.client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    Log.e(TAG, "Kotatsu katalog çekilemedi (HTTP ${response.code})")
                    return@withContext KotatsuExtensionAdapter.getSourceCount()
                }
                response.body?.string()
            } ?: return@withContext KotatsuExtensionAdapter.getSourceCount()

            // 3) KotatsuExtensionAdapter'ı güncelle
            val sources = KotatsuExtensionAdapter.loadSources(body)
            prefs.edit().putString(KEY_LAST_KOTATSU_SHA, latestSha).apply()
            Log.i(TAG, "Kotatsu kaynakları güncellendi: ${sources.size} kaynak (SHA: $latestSha)")
            sources.size
        } catch (e: Exception) {
            Log.e(TAG, "Kotatsu katalog indirme hatası: ${e.message}", e)
            KotatsuExtensionAdapter.getSourceCount()
        }
    }

    /**
     * kotatsu-parsers-redo reposunun en son commit SHA'sını GitHub API'dan çeker.
     */
    private fun fetchLatestCommitSha(networkHelper: NetworkHelper): String? {
        return try {
            val req = Request.Builder()
                .url(KOTATSU_COMMIT_API)
                .header("Accept", "application/vnd.github.sha")
                .build()
            networkHelper.client.newCall(req).execute().use { response ->
                if (!response.isSuccessful) return null
                val sha = response.body?.string()?.trim()
                if (sha.isNullOrBlank() || sha.length < 7) null
                else sha.take(10)
            }
        } catch (e: Exception) {
            Log.w(TAG, "fetchLatestCommitSha hata: ${e.message}")
            null
        }
    }

    // ─── Durum sorguları ──────────────────────────────────────────────────────

    fun getLastKotatsuCommitSha(context: Context): String =
        context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            .getString(KEY_LAST_KOTATSU_SHA, "") ?: ""

    fun getKotatsuSourceCount(): Int = KotatsuExtensionAdapter.getSourceCount()

    fun getKotatsuTrSources(): List<KotatsuMangaSource> =
        KotatsuExtensionAdapter.getSourcesByLang("tr")
}
